Documentation for ramble mirror
GoogleCloudPlatform/ramble pull request #216
Opened 2023-07-14 00:29 UTC by dodecatheon

Basic documentation for mirror usage.

2023-07-14 23:04 UTC, dodecatheon commented
Added tutorial, rebased, squashed changes. Ready for review.

2023-07-17 14:51 UTC, douglasjacobsen requested changes
I'd like @rfbgo to review this too, to make sure the rst format is correct for sphinx.

2023-07-17 14:51 UTC, douglasjacobsen commented on lib/ramble/docs/mirror-config.rst
> +Since Ramble input mirrors are intended to for use by applications, and applications are used
`to for use` --> `to be used`

2023-07-17 14:53 UTC, rfbgo commented
> I'd like @rfbgo to review this too, to make sure the rst format is correct for sphinx.

I'd rather not be the human rst format parser. Can we just have someone run the document generation and confirm it renders properly + no new warnings are added?

I am certainly able to do that, but in general would prefer it's on the contributor to uphold high standards (when they're internal)

2023-07-17 16:57 UTC, dodecatheon commented on lib/ramble/docs/mirror-config.rst
> +Since Ramble input mirrors are intended to for use by applications, and applications are used
Done

2023-07-17 16:57 UTC, dodecatheon commented on lib/ramble/docs/tutorials/mirrors.rst
> +For the purpose of this demonstration, I will assume that you're using
This plus related wording changes, done

2023-07-17 16:57 UTC, dodecatheon commented on lib/ramble/docs/tutorials/mirrors.rst
> +Once a mirror has been created locally, follow the directions in :ref:`Mirror use <mirror-use>`_ to use
This plus related wording changes, done

2023-07-17 16:58 UTC, dodecatheon commented on lib/ramble/docs/mirror-config.rst
> +Once ramble input and spack software mirrors have been created, the user wishing to speed
I've reworded slightly based on your comment. Hopefully it now conveys the idea better.

2023-07-17 17:32 UTC, dodecatheon commented
Found a broken ref after running sphinx and fixed it.

2023-07-17 17:57 UTC, douglasjacobsen requested changes
Thanks for the changes. They look better. One more nit, but otherwise LGTM.

2023-07-17 17:57 UTC, douglasjacobsen commented on lib/ramble/docs/mirror-config.rst
> +Once ramble input and spack software mirrors have been created, the user wishing to speed
I'd still rather not point this at speeding up an installation. The goal of the mirror is not to simply speed up access to source downloads and input files. It also allows you to create backups if they don't exist externally, or provide access to machines without internet access.

2023-07-17 18:07 UTC, dodecatheon commented on lib/ramble/docs/mirror-config.rst
> +Once ramble input and spack software mirrors have been created, the user wishing to speed
More rewording.

2023-07-17 18:08 UTC, dodecatheon commented
Rewording should have addressed requested changes.

2023-07-17 18:22 UTC, douglasjacobsen approved these changes

2023-07-17 18:23 UTC, merged