Add command-line control over workspace actions
GoogleCloudPlatform/ramble pull request #258
Opened 2023-09-08 21:51 UTC by douglasjacobsen

This merge adds the ability for workspace actions to filter which experiments they should act on within the workspace. This is performed through the `--where` and `--exclude-where` arguments.

Additionally, the logic around pipelines is overhauled in this merge to make it easier to extend and manipulate the pipelines.

2023-09-08 21:52 UTC, douglasjacobsen commented
I need to update the docs for this, but I think the code is ready to review now.

2023-09-10 01:29 UTC, douglasjacobsen commented
It would probably be good to get an extra thorough review of https://github.com/GoogleCloudPlatform/ramble/pull/258/files#diff-30efb4962f087cdf7750874e43ce62c7a1475c75cf7f1f2d315ccf6dbc22e398R586-R607

And it might be good to have a discussion around if we want hashes to be computed on dry-runs or not.

Currently, the logic as implemented will allow the hash to change between a dry-run and a full run of `ramble workspace setup`.

2023-09-18 19:23 UTC, rfbgo requested changes
Awesome contribution! Few small areas of feedback

2023-09-18 19:23 UTC, rfbgo commented on lib/ramble/ramble/pipeline.py
> +        # FIXME: this will fire the analyze logic of twice currently
This is in the wrong place, I think (or at least the upload_results doesn't trigger analyze) 

We can probably just remove it..

2023-09-18 21:15 UTC, douglasjacobsen commented on lib/ramble/ramble/cmd/workspace.py
> +    pipeline_cls = ramble.pipeline.pipeline_class(current_pipeline)
This actually does return a class, but the comment in the factory was wrong. I updated it in the latest commit.

2023-09-18 23:49 UTC, rfbgo approved these changes

2023-09-18 23:49 UTC, merged