Add documentation on disable_passthrough
GoogleCloudPlatform/ramble pull request #381
Opened 2024-01-23 22:21 UTC by dapomeroy

Adds documentation on the disable_passthrough config option

2024-01-23 22:23 UTC, dapomeroy commented
What do you think about having optional config settings (like disable passthrough and the repeats config) nested in subheadings of the config section? In the repeats PR, I put the repeats section at the end of configuration_files but I'm starting to think that's kind of an awkward place for it when it's separate from the 'config' section

2024-01-24 16:30 UTC, douglasjacobsen requested changes
I think having the config options nested under the config section header is a great idea. It helps keep the discussion around what they do and how to use them neatly contained.

2024-01-25 20:05 UTC, dapomeroy commented on lib/ramble/docs/configuration_files.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Done

2024-01-25 20:20 UTC, douglasjacobsen approved these changes

2024-01-25 20:20 UTC, merged