Add dev guides for modifiers and package managers
GoogleCloudPlatform/ramble pull request #558
Opened 2024-07-10 16:55 UTC by douglasjacobsen

2024-07-10 17:48 UTC, linsword13 reviewed
Thanks for writing these up, super informative! Some nits and typos but otherwise LGTM.

2024-07-10 17:48 UTC, linsword13 commented on lib/ramble/docs/dev_guides/modifier_dev_guide.rst
> +modifier definitions that are proided to the community. One of the modifier
provided

2024-07-10 17:48 UTC, linsword13 commented on lib/ramble/docs/dev_guides/modifier_dev_guide.rst
> +properly. Modifiers can define software packages they both will install with
"they both install..." somehow sounds a bit weird ;)

2024-07-10 17:48 UTC, linsword13 commented on lib/ramble/docs/dev_guides/modifier_dev_guide.rst
> +the ``executable_modification`` directive. Some modifiers will require the
Is it `executable_modifiers`?

2024-07-10 17:48 UTC, linsword13 commented on lib/ramble/docs/dev_guides/modifier_dev_guide.rst
> +``CommandExecutable`` objects, which are injected before and after the each
Redundant "the"

2024-07-10 17:48 UTC, linsword13 commented on lib/ramble/docs/dev_guides/modifier_dev_guide.rst
> +This are several directives that are shared between applications and modifiers.
"There are"

2024-07-10 17:48 UTC, linsword13 commented on lib/ramble/docs/dev_guides/package_manager_dev_guide.rst
> +After a package managers's ``package_manager.py`` file is created, Ramble's
Extra "s"

2024-07-10 17:48 UTC, linsword13 commented on lib/ramble/docs/dev_guides/package_manager_dev_guide.rst
> +can have dependencies, and and be injected either at the beginning or end of
"and" -> "can"

2024-07-10 17:48 UTC, linsword13 commented on lib/ramble/docs/dev_guides/package_manager_dev_guide.rst
> +package managers can be used as a reference.
I don't know if it'd be worthwhile to mention the existing unit-test support in `known_applications` for dry-run test package managers?

2024-07-10 18:15 UTC, douglasjacobsen commented
Thanks for catching those. Fixed in the latest commit.

2024-07-10 18:18 UTC, linsword13 approved these changes, later dismissed

2024-07-10 18:58 UTC, rfbgo requested changes

2024-07-10 18:58 UTC, rfbgo commented on lib/ramble/docs/dev_guides/modifier_dev_guide.rst
> +Modifier definitions files represent standardized objects which can be composed
```suggestion
Modifier definition files represent standardized objects which can be composed
```

2024-07-10 18:58 UTC, rfbgo commented on lib/ramble/docs/dev_guides/modifier_dev_guide.rst
> +Some of the information you need to gather before writing your modifier includes:
```suggestion
Some of the information you need to gather before writing your modifier include:
```
Mix of plural and singular here currently :)

2024-07-12 16:00 UTC, rfbgo approved these changes

2024-07-12 16:33 UTC, linsword13 approved these changes

2024-07-12 16:33 UTC, merged