Add orca app definition to the builtin repo
GoogleCloudPlatform/ramble pull request #616
Opened 2024-08-19 23:58 UTC by linsword13

Also add an example deck archive from the orca-input [library](https://sites.google.com/site/orcainputlibrary/setting-up-orca) as a demo workload.

Example run:

```sh
// example ramble.yaml
$ cat $RAMBLE_WORKSPACE/configs/ramble.yaml
ramble:
  variants:
    package_manager: spack
  variables:
    mpi_command: ''
    batch_submit: '{execute_experiment}'
  applications:
    orca:
      workloads:
        standard:
          experiments:
            test:
              variables:
                n_nodes: 1
                processes_per_node: 1
  software:
    packages:
      gcc13:
        pkg_spec: gcc@13.2.0 target=x86_64
        compiler_spec: gcc@13.2.0
      orca:
        pkg_spec: orca@5.0.4
      openmpi:
        pkg_spec: openmpi@4.1.2
        compiler: gcc13
    environments:
      orca:
        packages:
        - orca
        - openmpi

$ cd ramble/var/ramble/repos/builtin/applications/orca
$ ramble workspace setup
$ ramble on
$ ramble workspace analyze -p
==> Streaming details to log:
==>   /usr/local/google/home/linsword/hpc-dev/ramble/var/ramble/workspaces/orca-test/logs/analyze.2024-08-19_16.44.16.out
==>   Analyzing 1 out of 1 experiments:
==> Experiment #1 (1/1):
==>     name: orca.standard.test
==>     root experiment_index: 1
==>     log file: /usr/local/google/home/linsword/hpc-dev/ramble/var/ramble/workspaces/orca-test/logs/analyze.2024-08-19_16.44.16/orca.standard.test.out
Experiment complete: 100%|====================================================================================================================================================================| Elapsed (s): 0.05
==>   Returning to log file: /usr/local/google/home/linsword/hpc-dev/ramble/var/ramble/workspaces/orca-test/logs/analyze.2024-08-19_16.44.16.out
==> Results are written to:
==>   /usr/local/google/home/linsword/hpc-dev/ramble/var/ramble/workspaces/orca-test/results.2024-08-19_16.44.16.txt
==> Results from the analysis pipeline:
From Workspace: orca-test (hash: b06a152fda34fec2c6f13902b6a5e994a593c1388175d1a643de572820730065)
Experiment orca.standard.test figures of merit:
  Status = SUCCESS
  Tags = ['quantum chemistry']
  default (null) context figures of merit:
    Total run time = 0 days 0 hours 0 minutes 6 seconds 308 msec

```

2024-08-20 14:44 UTC, douglasjacobsen requested changes
Thanks for this! The app definition looks great. One question about the auxiliary tar, but otherwise LGTM.

2024-08-20 14:44 UTC, douglasjacobsen commented on var/ramble/repos/builtin/applications/orca/example_deck.tar.gz
Instead of having the tar in this repo, can we have the application definition just write this text into the experiment run directory?

Either as an executable on the workload, or it could override the `get_inputs` phase to just write the input into the correct inputs directory (for a given workload name).

2024-08-20 21:36 UTC, linsword13 commented on var/ramble/repos/builtin/applications/orca/example_deck.tar.gz
Thanks for the suggestion. I got rid of the tar file as discussed.

2024-08-21 17:03 UTC, douglasjacobsen approved these changes

2024-08-21 17:03 UTC, merged