Create Cloud-build tutorial triggers
GoogleCloudPlatform/ramble pull request #647
Opened 2024-09-13 17:36 UTC by douglasjacobsen

This merge adds cloud-build triggers for running through the ramble tutorials, to ensure they function the way they should.

2024-09-13 22:03 UTC, dapomeroy requested changes
Looks good overall, as far as I can tell without having specific experience on cloud build triggers. A couple of minor issues.

2024-09-13 22:03 UTC, dapomeroy commented on share/ramble/cloud-build/tutorials/ramble-tutorial-10.yaml
> +        ramble workspace create -d modifiers_wrf -c /workspace/examples/tutorial_10_lscpu_config.yaml
The tutorials use `workspace create` without the `-d` flag. Would it make sense to have one of these triggers run that workflow so that we test both? Or not necessary since it's already so well tested?

2024-09-13 22:03 UTC, dapomeroy commented on share/ramble/cloud-build/tutorials/ramble-tutorial-10.yaml
> +        ramble workspace activate ./modifiers_wrf
Do we need to have one of these triggers run the `create -a` flag instead of the separate `activate` command? It's shown several times in the tutorials

2024-09-13 22:03 UTC, dapomeroy commented on share/ramble/cloud-build/tutorials/ramble-tutorial-5.yaml
> +        cp /workspace/examples/vector_gromacs_software_config.yaml vector_gromacs/configs/ramble.yaml
Does this line need to be here in Tutorial 5? The workspace was set up using this same yaml file.

2024-09-13 22:03 UTC, dapomeroy commented on share/ramble/cloud-build/tutorials/ramble-tutorial-6.yaml
> +        ramble workspace info --expansions
Tutorial 6 doesn't use the `--expansions` flag (4 does), but it does have `ramble workspace concretize`. Should this line be concretize instead?

2024-09-13 22:03 UTC, dapomeroy commented on share/ramble/cloud-build/tutorials/ramble-tutorial-6.yaml
> +        ramble config add "variables:processes_per_node:4"
I wasn't sure what this was until I saw the comment in Tutorial 9: "# Cloud build VMs only have 4 cores". Can you add this comment for each tutorial that uses this config?

2024-09-13 22:03 UTC, dapomeroy commented on share/ramble/cloud-build/tutorials/ramble-tutorial-6.yaml
> +        ramble on --where '{n_nodes} == 1'
Presumably this is also because cloud build VMs are 4 core / 1 node?

2024-09-13 22:03 UTC, dapomeroy commented on share/ramble/cloud-build/tutorials/ramble-tutorial-10.yaml
> +        cp /workspace/exmaples/tutorial_10_aps_error_config.yaml modifiers_wrf/configs/ramble.yaml
Typo `exmaples`

2024-09-13 22:03 UTC, dapomeroy commented on share/ramble/cloud-build/tutorials/ramble-tutorial-10.yaml
> +        cp /workspace/exmaples/tutorial_10_aps_final_config.yaml modifiers_wrf/configs/ramble.yaml
Typo

2024-09-16 19:47 UTC, douglasjacobsen reviewed
Thanks for the comments! All done! :)

2024-09-16 19:47 UTC, douglasjacobsen commented on share/ramble/cloud-build/tutorials/ramble-tutorial-10.yaml
> +        ramble workspace create -d modifiers_wrf -c /workspace/examples/tutorial_10_lscpu_config.yaml
Good suggestion!

2024-09-16 19:47 UTC, douglasjacobsen commented on share/ramble/cloud-build/tutorials/ramble-tutorial-10.yaml
> +        ramble workspace activate ./modifiers_wrf
Good suggestion, added this.

2024-09-16 19:47 UTC, douglasjacobsen commented on share/ramble/cloud-build/tutorials/ramble-tutorial-5.yaml
> +        cp /workspace/examples/vector_gromacs_software_config.yaml vector_gromacs/configs/ramble.yaml
The workspace was created with `vector_matrix_gromacs_config.yaml` while this one copies in `vector_gromacs_software_config.yaml`.

2024-09-16 19:47 UTC, douglasjacobsen commented on share/ramble/cloud-build/tutorials/ramble-tutorial-6.yaml
> +        ramble config add "variables:processes_per_node:4"
Done!

2024-09-16 19:47 UTC, douglasjacobsen commented on share/ramble/cloud-build/tutorials/ramble-tutorial-6.yaml
> +        ramble on --where '{n_nodes} == 1'
This is more because cloud build doesn't setup clusters, and I don't want to run 2 node jobs on one cloud build node.

2024-09-16 20:56 UTC, dapomeroy approved these changes

2024-09-16 20:56 UTC, merged