Convert spack_setup to builtins
GoogleCloudPlatform/ramble pull request #71
Opened 2023-03-15 21:17 UTC by douglasjacobsen

This merge migrates the previously defined `spack_setup` variable to use builtins that are registered in the spack application class.

These are automatically added to all spack application instances.

Additionally, a `builtin::spack_deactivate` builtin is added, to help with more complicate spack experiments that might need to deactivate and reactivate spack environments.

2023-03-15 21:54 UTC, dodecatheon requested changes
Fails flake8 test

2023-03-15 21:55 UTC, dodecatheon requested changes
Overall, looks good to me. One question: do the current tests cover new lines of code? If so, you can mark as addressed once flake8 error is fixed.

2023-03-15 22:30 UTC, douglasjacobsen commented
@dodecatheon With the exception of the `spack_deactivate` builtin yes.

coverage report says:
`lib/ramble/ramble/application_types/spack.py                                      171     62    64%   23, 27, 68-81, 110, 160-164, 179, 187, 222-223, 227-281, 298`

2023-03-15 23:02 UTC, dodecatheon approved these changes

2023-03-15 23:03 UTC, merged

2023-03-16 15:02 UTC, rfbgo commented
Pretty sure this breaks the location in the rendered execution where the `spack_setup` is emitted, which may be troublesome. Will follow up offline